# Generated by Django 5.2.6 on 2025-09-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0006_alter_choice_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='category',
            field=models.CharField(default='Not Mentioned', max_length=20),
        ),
    ]
