# Generated by Django 5.2.6 on 2025-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0007_choice_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='category',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='Python', max_length=20),
        ),
    ]
