# Generated by Django 5.2.6 on 2025-09-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0008_remove_choice_category_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='band',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
