# Generated by Django 5.2.6 on 2025-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0010_user_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registry',
            name='Points',
            field=models.JSONField(default=list, null=True),
        ),
    ]
