# Generated by Django 5.2.6 on 2025-09-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0011_alter_user_registry_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registry',
            name='Points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
