# Generated by Django 5.2.6 on 2025-09-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0012_alter_user_registry_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registry',
            name='Points',
        ),
    ]
