# Generated by Django 5.2.6 on 2025-09-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_page', '0013_remove_user_registry_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_created=True, auto_now_add=True)),
                ('Name', models.CharField(max_length=20)),
                ('Score', models.IntegerField()),
                ('User_Registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Score_Board', to='first_page.user_registry')),
            ],
        ),
    ]
